# Curriculum Review


In [13]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

## Carnival Dice Rolls
    You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).
    You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.
    Assuming the dice are fair, should you play this game? How would this change if the winning condition was a sum greater than or equal to 12?

In [14]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4, 5],
       [6, 3, 1],
       [1, 2, 2],
       ...,
       [6, 2, 1],
       [3, 4, 3],
       [4, 2, 4]])

In [15]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([15, 10,  5, ...,  9, 10, 10])

In [17]:
wins = sums_by_trial > 12
wins

array([ True, False, False, ..., False, False, False])

In [18]:
wins.mean()

0.2633

In [19]:
# not necessary, just do mean and it will treat Trues and 1 and False as 0
win_rate = wins.astype(int).mean()
win_rate

0.2633

In [20]:
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.0505000000000004

In [21]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.5860000000000003

## No Rest or Relaxation
    There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all? 

In [22]:
p_nap = .3
ndays = ncols = 2
n_simulated_weekends = nrows = 10**5

In [23]:
data = np.random.random((nrows, ncols))
data

array([[0.46762045, 0.70078355],
       [0.18897809, 0.54312897],
       [0.253291  , 0.43836437],
       ...,
       [0.15008559, 0.37577491],
       [0.34690321, 0.58934311],
       [0.97135998, 0.57219933]])

In [24]:
naps = data < p_nap
naps

array([[False, False],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [False, False],
       [False, False]])

In [25]:
naps.sum(axis=1)

array([0, 1, 1, ..., 1, 0, 0])

In [26]:
(naps.sum(axis=1) >= 1).mean()

0.50998

In [27]:
(naps.sum(axis=1) == 0).mean()

0.49002

## One With Dataframes
    Let's take a look at one more problem:
    What is the probability of getting at least one 3 in 3 dice rolls?

In [41]:
n_simulations = nrows = 10**5
n_dice_rolled = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)
rolls

array([[3, 3, 6],
       [5, 3, 2],
       [4, 4, 6],
       ...,
       [5, 4, 1],
       [5, 2, 4],
       [1, 1, 6]])

In [42]:
pandarolls = pd.DataFrame(rolls)
pandarolls.head()

0  1  2
0  3  3  6
1  5  3  2
2  4  4  6
3  6  2  1
4  3  6  4

In [43]:
boolpandarolls = pandarolls.apply(lambda row: 3 in row.values, axis=1)
boolpandarolls.head()

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [44]:
boolpandarolls.mean()

0.42251

# Exercises

#### 1. How likely is it that you roll doubles when rolling two dice?


If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, P(woman taller than man)?
When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?